import Foundation

let dadJokes: [String] = [
    "3.14 percent of sailors are pi-rates.",
    "5/4 of people admit they’re bad at fractions.",
    "A bartender broke up with her boyfriend, but he kept asking her for another shot.",
    "A brain walks into a bar and takes a seat. “I’d like some wings and a pint of beer, please,” it says. “Sorry, but I can’t serve you,” the bartender replies. “You’re out of your head.”",
    "A cheeseburger walks into a bar. The bartender says, 'Sorry, we don't serve food here.'",
    "A college education now costs $100,000, but it produces three very proud people: the student, his mama, and his pauper.",
    "A couple of cups of yogurt walk into a country club. “We don’t serve your kind here,” the bartender says. “Why not?” one yogurt asks. “We’re cultured.”",
    "A friend of mine didn’t pay his exorcist. He got repossessed.",
    "A friend of mine is known for sweeping girls off their feet. He’s an extremely aggressive janitor.",
    "A guy walks into a bar, and there’s a horse serving drinks. The horse asks, “What are you staring at? Haven’t you ever seen a horse tending bar before?” The guy says, “It’s not that. I just never thought the parrot would sell the place.”",
    "A guy walks into a bar...and he was disqualified from the limbo contest.",
    "A pirate walks into a bar with a paper towel on his head. The bartender says, “What’s with the paper towel?” The pirate says, “Arrr! I’ve got a Bounty on me head!”",
    "A turtle is crossing the road when he’s mugged by two snails. When the police ask him what happened, the shaken turtle replies, “I don’t know. It all happened so fast.”",
    "Armed robbers—some say they’re a drain on society, but you’ve got to give it to them.",
    "Barbers…you have to take your hat off to them.",
    "Can February March? No, but April May!",
    "Cooking out this weekend? Don’t forget the pickle. It’s kind of a big dill.",
    "Dad, can you put my shoes on? No, I don't think they'll fit me.",
    "Dad, can you put the cat out? I didn't know it was on fire.",
    "Dad, did you get a haircut? No, I got them all cut!",
    "Dad: Did you hear about the kidnapping at school? Son: No. What happened? Dad: The teacher woke him up.",
    "Daughter: I have a lot of friends named Nathan. There’s Nathan Miller, Nathan Radcliff, Nathan Lewis… Me: When they are together, do you call them the United Nathans?",
    "Dear Math, grow up and solve your own problems.",
    "Did I tell you the time I fell in love during a backflip? I was heels over head!",
    "Did you hear about the aquatic sea mammals that escaped from the zoo? It was otter chaos.",
    "Did you hear about the circus fire? It was in tents.",
    "Did you hear about the guy who froze to death at the drive-in? He went to see Closed for the Winter.",
    "Did you hear about the guy who invented the knock-knock joke? He won the 'no-bell' prize.",
    "Did you hear about the guy who stole 50 cartons of hand sanitizer? They couldn’t prosecute—his hands were clean.",
    "Did you hear about the kidnapping at school? It’s fine, he woke up.",
    "Did you hear about the nurse who was chewed out by the doctor because she was absent without gauze?",
    "Did you hear about the restaurant on the moon? Great food, no atmosphere.",
    "Did you hear about the surgeon who enjoyed performing quick surgeries on insects? He did one on the fly.",
    "Did you hear the one about the kid who started a business tying shoelaces on the playground? It was a knot-for-profit.",
    "Did you hear the rumor about butter? Well, I’m not going to spread it!",
    "Did you hear they arrested the devil? Yeah, they got him on possession.",
    "Did you know corduroy pillows are in style? They're making headlines.",
    "Do I enjoy making courthouse puns? Guilty.",
    "Do mascara and lipstick ever argue? Sure, but then they makeup.",
    "Do you wanna box for your leftovers? No, but I'll wrestle you for them.",
    "Dogs can’t operate MRI machines. But catscan.",
    "Don't trust atoms. They make up everything!",
    "Have you ever tried to catch a fog? I tried yesterday but I mist.",
    "Have you heard about the chocolate record player? It sounds pretty sweet.",
    "How can you tell if a tree is a dogwood tree? By its bark.",
    "How did the dad prank his daughter using fake dog poop on April Fools Day? He told her to look out for her new sham-poo in the shower.",
    "How do celebrities stay cool? They have many fans.",
    "How do lawyers say goodbye? We'll be suing ya!",
    "How do you follow Will Smith in the snow? You follow the fresh prints.",
    "How do you get a country girl’s attention? A tractor.",
    "How do you get a good price on a sled? You have toboggan.",
    "How do you get a squirrel to like you? Act like a nut.",
    "How do you make 7 even? Take away the s.",
    "How do you make a Kleenex dance? Put a little boogie in it!",
    "How do you make a tissue dance? You put a little boogie in it.",
    "How do you make holy water? You boil the hell out of it.",
    "How do you row a canoe filled with puppies? Bring out the doggy paddle.",
    "How do you tell the difference between an alligator and a crocodile? You will see one later and one in a while.",
    "How do you weigh a millennial? In Instagrams.",
    "How does a penguin build his house? Igloos it together.",
    "How does a taco say grace? Lettuce pray.",
    "How does the man in the moon get his hair cut? Eclipse it.",
    "How long should socks be? Twelve inches, so you can fit in one foot.",
    "How many DIY buffs does it take to change a light bulb? One, but it takes two weeks and four trips to the hardware store.",
    "How many mystery writers does it take to change a light bulb? Two: One to screw it in most of the way and another to give it a surprise twist at the end.",
    "How many narcissists does it take to screw in a light bulb? One. The narcissist holds the light bulb while the rest of the world revolves around him.",
    "How many paranoids does it take to change a light bulb? Who wants to know?",
    "How many tickles does it take to make an octopus laugh? Ten tickles.",
    "How much does it cost Santa to park his sleigh? Nothing, it's on the house.",
    "How was the handsome runner described? “Dashing.”",
    "I asked my dog what's two minus two. He said nothing.",
    "I began to read a horror novel in braille. Something bad is about to happen—I can feel it.",
    "I can guess what people do for a living just by looking at their hands. I mean, I’m usually wrong, but I can guess.",
    "I could tell a joke about pizza, but it's a little cheesy.",
    "I decided to sell my vacuum cleaner—it was just gathering dust!",
    "I didn’t get a haircut, I got them all cut.",
    "I don’t trust stairs. They are always up to something.",
    "I don't play soccer because I enjoy the sport. I'm just doing it for kicks!",
    "I don't trust those trees. They seem kind of shady.",
    "I got carded at a liquor store, and my Blockbuster card accidentally fell out. The cashier said never mind.",
    "I got hit in the head with a can of Coke today. Don’t worry, I’m not hurt. It was a soft drink.",
    "I had a date last night. It was perfect. Tomorrow, I’ll try a grape.",
    "I had a neck brace fitted years ago and I've never looked back since.",
    "I have a joke about chemistry, but I don't think it will get a reaction.",
    "I know a bunch of good jokes about umbrellas, but they usually go over people’s heads.",
    "I know a lot of jokes about retired people, but none of them work.",
    "I know a surgeon who puts organs back in upside down. I told him that’s not funny, but he said it was an inside joke.",
    "I like telling Dad jokes. Sometimes he laughs!",
    "I lost my job at the bank on my first day. A woman asked me to check her balance, so I pushed her over.",
    "I made a pencil with two erasers. It was pointless.",
    "I once got fired from a canned juice company. Apparently I couldn't concentrate.",
    "I once had a dream I was floating in an ocean of orange soda. It was more of a fanta sea.",
    "I only know 25 letters of the alphabet. I don't know y.",
    "I ordered a chicken and an egg from Amazon. I'll let you know...",
    "I read that by law you must turn on your headlights when it’s raining in Sweden, but how am I supposed to know when it’s raining in Sweden?",
    "I recently went to the “World’s Tiniest Wind Turbine” exhibit. Honestly, not a big fan.",
    "I searched for a lighter on Amazon, but all I could find were 6,000 matches.",
    "I signed up for a marathon, but how will I know if it’s the real deal or just a run through?",
    "I sold our vacuum cleaner; it was just gathering dust.",
    "I spent a lot of time, money, and effort childproofing my house, but the kids still get in.",
    "I tell dad jokes, but I don’t have any kids. I’m a faux pa.",
    "I thought the dryer was shrinking my clothes. Turns out it was the refrigerator all along.",
    "I told my doctor I heard buzzing, but he said it’s just a bug going around.",
    "I told my girlfriend she drew on her eyebrows too high. She seemed surprised.",
    "I used to be a personal trainer. Then I gave my too weak notice.",
    "I used to be addicted to soap, but I'm clean now.",
    "I used to hate facial hair, but then it grew on me.",
    "I used to play piano by ear. Now I use my hands.",
    "I want to go on record that I support farming. As a matter of fact, you could call me protractor.",
    "I want to make a brief joke, but it’s a little cheesy.",
    "I was addicted to the hokey pokey…but I turned myself around.",
    "I was breastfed until 3. But enough about my day, how was yours?",
    "I was going to tell a time-traveling joke, but you guys didn’t like it.",
    "I was just reminiscing about the beautiful herb garden I had when I was growing up. Good thymes.",
    "I was out on a walk when I saw a sign that said, “Man wanted for robbery.” So I went in and applied for the job.",
    "I wondered why the ball was getting bigger. Then it hit me.",
    "I wouldn't buy anything with velcro. It's a total rip-off.",
    "I’m an expert at picking leaves and heating them in water. It’s my special tea.",
    "I’m reading a novel where the main character has strained the muscles around his spine. That’s his back story.",
    "I’m so good at sleeping, I can do it with my eyes closed.",
    "I’ve been bored recently, so I decided to take up fencing. The neighbors keep demanding that I put it back.",
    "I’ve been breeding racing deer. Just trying to make a quick buck.",
    "I’ve been thinking about taking up meditation. I figure it’s better than sitting around doing nothing.",
    "If a child refuses to nap, are they guilty of resisting a rest?",
    "If April showers bring May flowers, what do May flowers bring? Pilgrims.",
    "If athletes get athlete’s foot, what do astronauts get? Missile toe.",
    "If the early bird gets the worm, I’ll sleep in until there’s pancakes.",
    "If you see a crime at an Apple Store, does that make you an iWitness?",
    "If you see a robbery at an Apple store, does that make you an iWitness?",
    "I'm afraid for the calendar. Its days are numbered.",
    "I'm on a seafood diet. I see food and I eat it.",
    "I'm reading a book about anti-gravity. It's impossible to put down!",
    "I'm so good at sleeping, I can do it with my eyes closed!",
    "In a freak accident today, a photographer was killed when a huge lump of cheddar landed on him. To be fair, the people who were being photographed did try to warn him.",
    "Inflation is really getting out of hand, but that’s just my five cents.",
    "Is this pool safe for diving? It deep ends.",
    "It hurts me to say this, but I have a sore throat.",
    "It takes guts to be an organ donor.",
    "It’s a shame that the Beatles didn’t make the submarine in that song green. That would’ve been sublime.",
    "It's inappropriate to make a 'dad joke' if you're not a dad. It's a faux pa.",
    "I've got a great joke about construction, but I'm still working on it.",
    "Justice is a dish best served cold. If it were served warm, it would be justwater.",
    "Mountains aren't just funny. They're hill areas.",
    "My boss told me to have a good day, so I went home.",
    "My dad told me a joke about boxing. I guess I missed the punch line.",
    "My dentist offered me dentures for only a dollar. It sounded like a good deal at the time, but now I have buck teeth.",
    "My doctor told me I’ve really grown as a person. Well, her exact words were that I “gained excess weight.”",
    "My dog accidentally swallowed a bunch of Scrabble tiles. I think this could spell disaster.",
    "My friend wants to become an archaeologist, but I’m trying to put him off. I’m convinced his life will be in ruins.",
    "My girlfriend says it’s either her or my career as a news reporter. I have some breaking news for her.",
    "My IQ test results came back. They were negative.",
    "My kid wants to invent a pencil with an eraser on each end, but I just don’t see the point.",
    "My son asked me to put his shoes on, but I don’t think they’ll fit me.",
    "My son has his BA and his MA, but his PA still supports him.",
    "My son’s fourth birthday was today. When he came to see me, I didn’t recognize him at first. I had never seen him be four.",
    "My wife asked me to go get 6 cans of Sprite from the grocery store. I realized when I got home that I had picked 7 up.",
    "My wife asked me to stop singing “Wonderwall” to her. I said maybe…",
    "My wife asked me to sync her phone, so I threw it into the ocean.",
    "My wife is really mad at the fact that I have no sense of direction. So I packed up my stuff and right!",
    "My wife is really mad that I have no sense of direction. I packed up my stuff and right.",
    "Not sure if you have noticed, but I love bad puns. That’s just how eye roll.",
    "People are usually shocked that I have a Police record. But I love their greatest hits!",
    "Police arrested a bottle of water because it was wanted in three different states: solid, liquid, and gas.",
    "RIP boiled water—you will be mist.",
    "Scientists have discovered what is believed to be the world’s largest bedsheet. More on this story as it unfolds.",
    "Shouldn’t the “roof” of your mouth actually be called the ceiling?",
    "Shout out to my fingers. I can count on all of them.",
    "Someone told me that I should write a book. I said, “That’s a novel concept.”",
    "Sore throats are a pain in the neck.",
    "Spring is here! I got so excited I wet my plants.",
    "Stop looking for the perfect match…use a lighter.",
    "Sundays are always a little sad, but the day before is a sadder day.",
    "Teacher: “There are two words I don’t allow in my class. One is gross, and the other is cool.” Johnny: “So, what are the words?”",
    "That car looks nice but the muffler seems exhausted.",
    "The bank keeps calling me to give me compliments. They say I have an “outstanding balance.”",
    "The past, the present, and the future walked into a bar. It was tense.",
    "The wedding was so beautiful, even the cake was in tiers.",
    "There’s only one thing I can’t deal with, and that’s a deck of cards glued together.",
    "This graveyard looks overcrowded. People must be dying to get in.",
    "Today, my son asked, “Can I have a bookmark?” I burst into tears—11 years old and he still doesn’t know my name is Brian.",
    "Two goldfish are in a tank. One says to the other, “Do you know how to drive this thing?”",
    "Two guys walked into a bar. The third guy ducked.",
    "Wanna hear a joke about paper? Never mind—it's tearable.",
    "Want to hear a joke about construction? I’m still working on it.",
    "Want to know why nurses like red crayons? Sometimes they have to draw blood.",
    "We all know about Murphy’s Law: Anything that can go wrong will go wrong. But have you heard of Cole’s Law? It’s thinly sliced cabbage.",
    "What animals are the best to call if you get locked out of your house? Monkeys.",
    "What country's capital is growing the fastest? Ireland. Every day it's Dublin.",
    "What did Baby Corn say to Mama Corn? Where's Pop Corn?",
    "What did one cannibal say to the other while they were eating a clown? Does this taste funny to you?",
    "What did one DNA say to the other DNA? “Do these genes make me look fat?”",
    "What did one Dorito farmer say to the other? “Cool Ranch!”",
    "What did one furniture maker say to another during a tense discussion? “Let’s table this.”",
    "What did one hat say to the other? Stay here! I'm going on ahead.",
    "What did one plate say to another plate? Tonight, dinner’s on me.",
    "What did one wall say to the other? I'll meet you at the corner.",
    "What did Tennessee? The same thing as Arkansas.",
    "What did the accountant say while auditing a document? This is taxing.",
    "What did the air conditioner say when it met a celebrity? “I’m a big fan.”",
    "What did the baker say when she won an award? “It was a piece of cake.”",
    "What did the coffee report to the police? A mugging.",
    "What did the dad say when his golden retriever was caught eating a hot dog? “It’s a dog eat dog world out there.”",
    "What did the dishwasher say to the oven after a productive day? “You’ve been on fire!”",
    "What did the drummer call his twin daughters? Anna One, Anna Two!",
    "What did the dryer say to the boring duvet cover that just got out of the washer? “Don’t be such a wet blanket.”",
    "What did the evil chicken lay? Deviled eggs.",
    "What did the fish say when he hit the wall? Dam.",
    "What did the flowers do when the bride walked down the aisle? They rose.",
    "What did the French chef give his wife for Valentine’s Day? A hug and a quiche.",
    "What did the geometry teacher say when the class had trouble solving a problem? “Let’s try a different angle.”",
    "What did the husband say to his wife right after getting LASIK surgery? “Aren’t you a sight for sore eyes?”",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "What did the juicer say to the orange during self-quarantine? Can’t wait to squeeze you!",
    "What did the ocean say to the beach? Nothing, it just waved.",
    "What did the police officer say to his belly-button? You’re under a vest.",
    "What did the sapphire’s best friend tell her? “You’re a real gem.”",
    "What did the skeleton order with its beer? A mop.",
    "What did the two pieces of bread say on their wedding day? It was loaf at first sight.",
    "What did the zero say to the eight? That belt looks good on you.",
    "What do a tick and the Eiffel Tower have in common? They're both Paris sites.",
    "What do Bostonians call a fake noodle? An impasta.",
    "What do clouds wear? Thunderwear.",
    "What do frogs use to track their exercise? Fit (rib)bits.",
    "What do lions use to look at their manes? Mirroars.",
    "What do sprinters eat before a race? Nothing—they fast.",
    "What do you call 26 letters that went for a swim? Alphawetical.",
    "What do you call 50 pigs and 50 deer? 100 sows and bucks.",
    "What do you call a bear with no teeth? A gummy bear.",
    "What do you call a belt made of watches? A waist of time.",
    "What do you call a dog that can do magic? A Labracabrador.",
    "What do you call a factory that makes okay products? A satisfactory.",
    "What do you call a fake noodle? An impasta.",
    "What do you call a fibbing cat? A lion.",
    "What do you call a fish wearing a bowtie? Sofishticated.",
    "What do you call a fish with no eye? A fsh.",
    "What do you call a hippie’s wife? Mississippi.",
    "What do you call a hot dog on wheels? Fast food!",
    "What do you call a lazy kangaroo? Pouch potato.",
    "What do you call a naughty lamb dressed up like a skeleton for Halloween? Baaad to the bone.",
    "What do you call a pony with a sore throat? A little hoarse.",
    "What do you call a poor Santa Claus? St. Nickel-less.",
    "What do you call a pudgy psychic? A four-chin teller.",
    "What do you call a snitching scientist? A lab rat.",
    "What do you call a toothless bear? A gummy bear!",
    "What do you call an angry musician flipping someone off? A song bird.",
    "What do you call an elephant that doesn't matter? An irrelephant.",
    "What do you call an unpredictable camera? A loose Canon.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "What do you call it when a group of apes starts a company? Monkey business.",
    "What do you call it when a lawyer takes a test early in the morning? A breakfast bar.",
    "What do you call it when a snowman throws a tantrum? A meltdown.",
    "What do you call someone who always states the obvious? Someone who always states the obvious.",
    "What do you call someone with no body and no nose? Nobody knows.",
    "What do you call two monkeys that share an Amazon account? Prime mates.",
    "What do you call two octopuses that look the same? Itenticle.",
    "What do you get from a pampered cow? Spoiled milk.",
    "What do you get when you cross a polar bear with a seal? A polar bear.",
    "What do you need to make a small fortune on Wall Street? A large fortune.",
    "What does “idk” stand for? Everyone I ask says, “I don’t know.”",
    "What does “Rockin’ Robin” do when she’s bored? Tweet.",
    "What does a bee use to brush its hair? A honeycomb!",
    "What does a house wear? Address.",
    "What does a karate master get rewarded with while driving? A seat belt.",
    "What does a lemon say when it answers the phone? Yellow!",
    "What does a mobster buried in cement soon become? A hardened criminal.",
    "What does a nosey pepper do? It gets jalapeño business.",
    "What does a sprinter eat before a race? Nothing, they fast!",
    "What does a writer have in common with a football player? Anxiety over a rough draft.",
    "What does garlic do when it gets hot? It takes its cloves off.",
    "What happens when a strawberry gets run over crossing the street? Traffic jam.",
    "What happens when it rains cats and dogs? You have to be careful not to step in a poodle.",
    "What has more letters than the alphabet? The post office!",
    "What has one head, one foot, and four legs? A bed.",
    "What invention allows us to see through walls? Windows.",
    "What is Marco’s favorite clothing store? Polo.",
    "What is the Easter bunny’s favorite type of music? Hip-hop.",
    "What is the most popular fish in the ocean? A starfish.",
    "What kind of bird is always getting hurt? The owl.",
    "What kind of car does a sheep like to drive? A lamborghini.",
    "What kind of car does an egg drive? A yolkswagen.",
    "What kind of cleaning product feels a lot of motivation in life? All-purpose.",
    "What kind of drink can be bitter and sweet? Reali-tea.",
    "What kind of music do chiropractors like? Hip pop.",
    "What kind of noise does a witch’s vehicle make? Brrrroooom, brrroooom.",
    "What kind of shape may have been knighted? Cir-cles.",
    "What kind of shoes do ninjas wear? Sneakers!",
    "What kind of shoes does a lazy person wear? Loafers.",
    "What kind of spells do leprechauns use? Lucky Charms.",
    "What makes a basketball court trendy and accessorized? The hoops.",
    "What part of the museum makes everyone sneeze? The sta-tues.",
    "What piece on the playground is always exhausted? The tire swing.",
    "What sound does a witch’s car make? Broom broom!",
    "What time did the man go to the dentist? Tooth hurt-y.",
    "What vegetable is kind to everyone? The sweet potato.",
    "What was said about the messy, angry man who was eating a can of Pringles? “He’s got a chip on his shoulder.”",
    "What was Sherlock Holmes’ favorite protein source? Mystery meat.",
    "What would the Terminator be called in his retirement? The Exterminator.",
    "What’s a bad wizard’s favorite computer program? Spell check.",
    "What’s a crafty dancer’s favorite hobby? Cutting a rug.",
    "What’s a vampire’s favorite ship? A blood vessel.",
    "What’s a writer’s favorite train station? Penn Station.",
    "What’s an astronaut’s favorite part of a computer? The space bar.",
    "What’s brown and sticky? A stick.",
    "What’s either a really gross animal issue OR an impressive, magical school? Hogwarts.",
    "What’s Forrest Gump’s password? 1forrest1",
    "What’s it called when kittens get stuck in a tree? A cat-astrophe.",
    "What’s orange and sounds like a parrot? A carrot.",
    "What’s red and smells like blue paint? Red paint.",
    "What’s the best way to watch a fly-fishing tournament? Live stream.",
    "What’s the difference between a man wearing pajamas on a bicycle and a guy wearing a tuxedo on a unicycle? Attire.",
    "What’s the least-spoken language in the world? Sign language.",
    "What’s the most detail-oriented ocean? The Pacific.",
    "What’s the most patriotic sport? Flag football.",
    "What’s the name of a very polite, European body of water? Merci.",
    "What's a robot's favorite snack? Computer chips.",
    "What's the best smelling insect? A deodor-ant.",
    "What's the best thing about Switzerland? I don't know, but the flag is a big plus.",
    "What's the best way to watch a fly fishing tournament? Live stream.",
    "When does a joke become a “dad joke”? When it becomes apparent.",
    "When I was a kid, my dad got fired from his job as a road worker for theft. I refused to believe he could do such a thing, but when I got home, the signs were all there.",
    "When two vegans get in an argument, is it still called a beef?",
    "When you have a bladder infection, urine trouble.",
    "Whenever I try to eat healthy, a chocolate bar looks at me and Snickers.",
    "Where do boats go when they're sick? To the boat doc.",
    "Where do fruits go on vacation? Pear-is!",
    "Where do math teachers go on vacation? Times Square.",
    "Where do wasps like to get lunch? A bee-stro.",
    "Where do you learn to make a banana split? Sundae school.",
    "Where do young trees go to learn? Elementree school.",
    "Where was the dripping coming from in the fridge? The leeks.",
    "Which bathroom appliance would be the worst life preserver? The sink.",
    "Which bear is the most condescending? A pan-duh!",
    "Which state has the most streets? Rhode Island.",
    "Which U.S. state is known for its especially small soft drinks? Minnesota.",
    "Why are elevator jokes so classic and good? They work on many levels.",
    "Why are piggy banks so wise? They're filled with common cents.",
    "Why are spiders so smart? They can find everything on the web.",
    "Why can't a nose be 12 inches long? Because then it would be a foot.",
    "Why can't you hear a psychiatrist using the bathroom? Because the 'P' is silent.",
    "Why couldn’t the bicycle stand up by itself? It was two-tired.",
    "Why couldn’t the couple get married at the library? It was all booked up.",
    "Why couldn’t the couple respond right away when looking at wedding venues? They were engaged.",
    "Why couldn’t the family leave the room after playing with Legos? They were blocked.",
    "Why couldn't the bicycle stand up by itself? It was two tired.",
    "Why did Beethoven get rid of his chickens? All they said was, “Bach, Bach, Bach…”",
    "Why did Billy get fired from the banana factory? He kept throwing away the bent ones.",
    "Why did the bedding hide their relationship? They just wanted something pillow-key!",
    "Why did the cashier rip money in half? They were asked to break a bill.",
    "Why did the coach go to the bank? To get his quarterback.",
    "Why did the envelope take so long to get ready? It had to get addressed.",
    "Why did the man fall down the well? Because he couldn’t see that well.",
    "Why did the man name his dogs Rolex and Timex? Because they were watchdogs.",
    "Why did the math book look so sad? Because of all of its problems!",
    "Why did the raisin go out with the prune? Because he couldn’t find a date.",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "Why did two tall people get along so well? The could really see eye to eye.",
    "Why didn’t Han Solo enjoy his steak dinner? It was Chewie.",
    "Why didn't the skeleton climb the mountain? It didn't have the guts.",
    "Why do cows wear bells? Because their horns don’t work.",
    "Why do dads feel the need to tell such bad jokes? They just want to help you become a groan up.",
    "Why do dogs float in water? Because they are good buoys.",
    "Why do melons have weddings? Because they cantaloupe.",
    "Why do nurses like red crayons? Sometimes they have to draw blood.",
    "Why do pumpkins sit on porches? They have no hands to knock on the door.",
    "Why do seagulls fly over the ocean? Because if they flew over the bay, we'd call them bagels.",
    "Why do some couples go to the gym? Because they want their relationship to work out.",
    "Why do you never see elephants hiding in trees? Because they’re so good at it.",
    "Why don’t phones ever go hungry? They have plenty of apps to choose from.",
    "Why don’t pirates take a bath before they walk the plank? They just wash up on shore.",
    "Why don't eggs tell jokes? They'd crack each other up.",
    "Why is cold water so insecure? Because it’s never called hot.",
    "Why is grass so dangerous? Because it’s full of blades.",
    "Why is Peter Pan always flying? Because he Neverlands.",
    "Why is sand so optimistic? It has a can-dune attitude.",
    "Why shouldn’t you write with a broken pencil? Because it’s pointless.",
    "Why was the color green notoriously single? It was always so jaded.",
    "Why was the cow such a heartthrob on the farm? He was a s-moo-th talker.",
    "Why was the dad sitting on a pack of playing cards? His kid asked him to sit on the deck.",
    "Why was the ghost so tired? He worked the graveyard shift.",
    "Why was the gossip disliked at the coffee shop? She always spilled the tea.",
    "Why was the hockey player gifted a new cap? He was known for his hat tricks.",
    "Why was the pig covered in ink? Because it lived in a pen.",
    "Why was the rookie police officer assigned to hunt the cannibal? The more seasoned officers had already been eaten.",
    "Why were spectators confused by the koala’s self-portrait? It was bear.",
    "Why were the utensils stuck together? They were spooning.",
    "Why would doors do well on social media? Everyone looks for their handles.",
    "You can’t plant flowers if you haven’t botany.",
    "You know, people say they pick their nose, but I feel like I was just born with mine.",
    "You think swimming with sharks is expensive? Swimming with sharks cost me an arm and a leg.",
    "You’re American when you go into a bathroom and when you come out, but what are you while you’re in the bathroom? European."
]
